context:
  version: "0.7.1"

package:
  name: rust-audit-info
  version: ${{ version }}

source:
  url: https://github.com/rust-secure-code/cargo-auditable/archive/refs/tags/v${{ version }}.tar.gz
  sha256: e79d1daba3d9a6fc37193d67c9442bd8f90c228c27ead1f21fb6e51630917527

build:
  number: 0
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - if: unix
        then:
          - cargo auditable install --no-track --locked --root ${PREFIX} --path rust-audit-info
          - cargo-bundle-licenses --format yaml --output ${SRC_DIR}/THIRDPARTY.yml
      - if: win
        then:
          - cargo auditable install --no-track --locked --root %PREFIX% --path rust-audit-info
          - if errorlevel 1 exit 1
          - cargo-bundle-licenses --format yaml --output %SRC_DIR%/THIRDPARTY.yml
          - if errorlevel 1 exit 1

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - cargo-bundle-licenses
    - cargo-auditable

tests:
  - package_contents:
      # No help command available
      bin:
        - rust-audit-info

about:
  homepage: https://github.com/rust-secure-code/cargo-auditable/tree/master/rust-audit-info
  repository: https://github.com/rust-secure-code/cargo-auditable
  documentation: https://github.com/rust-secure-code/cargo-auditable/tree/master/rust-audit-info
  summary: Command-line tool to extract the dependency trees embedded in binaries by cargo auditable.
  license: Apache-2.0 OR MIT
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - xhochy
